edition = "2018"
merge_imports = true

# The "Default" setting has a heuristic which splits lines too aggresively.
# Bugs:
#   * https://github.com/rust-lang/rustfmt/issues/3119
#   * https://github.com/rust-lang/rustfmt/issues/3120

use_small_heuristics = "Max"

# Prevent carriage returns
newline_style = "Unix"
